export const mockData = {
  users: [
    {
      id: "1",
      name: "Andre Faria Ruaro",
      email: "andre.ruaro@unesc.net",
      user: "andre.ruaro",
      pwd: "admin123",
      level: "admin",
      status: "on",
    },
    {
      id: "2",
      name: "Maria Silva Santos",
      email: "maria.santos@unesc.net",
      user: "maria.santos",
      pwd: "user123",
      level: "user",
      status: "on",
    },
    {
      id: "3",
      name: "João Pedro Oliveira",
      email: "joao.oliveira@unesc.net",
      user: "joao.oliveira",
      pwd: "user123",
      level: "user",
      status: "off",
    },
  ],
  teachers: [
    {
      id: "1",
      name: "Judite Heeler",
      school_disciplines: "Artes, Português",
      contact: "j.heeler@gmail.com",
      phone_number: "48 9696 5858",
      status: "on",
    },
    {
      id: "2",
      name: "Carlos Eduardo Silva",
      school_disciplines: "Matemática, Física",
      contact: "carlos.silva@gmail.com",
      phone_number: "48 9999 1234",
      status: "on",
    },
    {
      id: "3",
      name: "Ana Paula Costa",
      school_disciplines: "História, Geografia",
      contact: "ana.costa@gmail.com",
      phone_number: "48 8888 5678",
      status: "on",
    },
  ],
  students: [
    {
      id: "1",
      name: "Bingo Heeler",
      age: "6",
      parents: "Bandit Heeler e Chilli Heeler",
      phone_number: "48 9696 5858",
      special_needs: "Síndrome de Down",
      status: "on",
    },
    {
      id: "2",
      name: "Bluey Heeler",
      age: "7",
      parents: "Bandit Heeler e Chilli Heeler",
      phone_number: "48 9696 5858",
      special_needs: "Autismo",
      status: "on",
    },
    {
      id: "3",
      name: "Muffin Heeler",
      age: "4",
      parents: "Stripe Heeler e Trixie Heeler",
      phone_number: "48 7777 9999",
      special_needs: "TDAH",
      status: "on",
    },
  ],
  professionals: [
    {
      id: "1",
      name: "Winton Blake",
      specialty: "Fisioterapeuta",
      contact: "wb.fisio@gmail.com",
      phone_number: "48 9696 5858",
      status: "on",
    },
    {
      id: "2",
      name: "Calypso Santos",
      specialty: "Psicóloga",
      contact: "calypso.psi@gmail.com",
      phone_number: "48 8888 7777",
      status: "on",
    },
    {
      id: "3",
      name: "Lucky Costa",
      specialty: "Fonoaudiólogo",
      contact: "lucky.fono@gmail.com",
      phone_number: "48 7777 6666",
      status: "on",
    },
  ],
  appointments: [
    {
      id: "1",
      specialty: "Fisioterapeuta",
      comments: "Realizar sessão de fisioterapia",
      date: "2024-01-15T16:00:00",
      student: "Bingo Heeler",
      professional: "Winton Blake",
    },
    {
      id: "2",
      specialty: "Psicóloga",
      comments: "Sessão de acompanhamento psicológico",
      date: "2024-01-16T14:00:00",
      student: "Bluey Heeler",
      professional: "Calypso Santos",
    },
    {
      id: "3",
      specialty: "Fonoaudiólogo",
      comments: "Terapia da fala",
      date: "2024-01-17T10:00:00",
      student: "Muffin Heeler",
      professional: "Lucky Costa",
    },
  ],
  events: [
    {
      id: "1",
      description: "Palestra bem viver com saúde",
      comments: "Profissionais de saúde da Unesc",
      date: "2024-01-20T16:00:00",
    },
    {
      id: "2",
      description: "Workshop sobre inclusão escolar",
      comments: "Capacitação para professores",
      date: "2024-01-25T14:00:00",
    },
    {
      id: "3",
      description: "Reunião de pais e responsáveis",
      comments: "Discussão sobre desenvolvimento dos alunos",
      date: "2024-01-30T19:00:00",
    },
  ],
}
